### ISSUE TITLE
Некорректная валидация для кораблей на нижней линии поля

### ISSUE THREAD

**Issue by mezhmal** [qwabra/qffg#1]
https://github.com/qwabra/qffg/blob/33e743c45e7a13e05827c45abfe97a1127b013e7/src/index.ts#L41

Предложенный Вами способ решения вполне хорош. Он не учитывает лишь возможность расположения кораблей на нижней линии поля. К примеру, попробуйте проявить проблему, переставив однопалубный (или любой другой) корабль на нижнюю линию. В этом случае валидатор пишет в консоль TypeError: "m[(i + 1)] is undefined"

Прошу это исправить

**Comment by qwabra** [comment]
> В этом случае валидатор пишет в консоль TypeError: "m[(i + 1)] is undefined"
хм, а у меня пишет:
> TypeError: Cannot read property '8' of undefined

ошибка в отсутствии проверки существования следующего ряда

https://github.com/qwabra/qffg/commit/f8c0de874f2161ff1887c02089d29e0f4716129d
